self.input_var4_create = QLineEdit(self)
self.input_var4_create.resize(35, 50)
self.input_var4_create.move(1100, 500)
self.input_var4_create.hide()
self.input_var4_create.setStyleSheet(input_StyleSheet)
